name: Naming Check
on:
  pull_request:
    paths: ["{0,1,2,3,4}*/*.md","{0,1,2,3,4}*.md","**/{0,1,2,3,4}*.md"]
jobs:
  check-names:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate naming
        run: |
          fail=0
          while IFS= read -r f; do
            base=$(basename "$f")
            # Допускаем файлы вида: "X.Y. Название.md" или "X.Y_Название.md"
            if ! echo "$base" | grep -Eq '^[0-4]\.[0-9]+\. [^/]+\.md$|^[0-4]\.[0-9]+_[^/]+\.md$|^[0-4]\.[0]\. Информация\.md$'; then
              echo "::warning file=$f::Проверьте формат имени (рекомендуется: 1.2. Название.md)"
            fi
          done < <(git diff --name-only --diff-filter=ACMR origin/main... | grep -E '\.md$' || true)
          exit 0
